name: reuse global ci
on:
  push:
  workflow_dispatch:
  
jobs:
  global-ci-resuse:
    uses: YannickGbaka/ci-commons/.github/workflows/resuable-ci.yml@master
    with: 
      phpversion: '8.1'
      slack-message: "The build number is ${{ github.sha }} : \nThe github repository number is : ${{ github.repository }}\n The workflow actor is ${{ github.autor }}"
    secrets:
      slackToken: ${{ secrets.SLACK_TOKEN }}


