name: reuse global ci
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
jobs:
  sonarqube:
    # - uses: actions/checkout@v3
    #   with:
    #     # Disabling shallow clones is recommended for improving the relevancy of reporting
    #     fetch-depth: 0
    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    uses: YannickGbaka/ci-commons/.github/workflows/resuable-ci.yml@master
    with:
      phpversion: '8.1'
      projectname: ${{ vars.PROJECT_NAME }}
      slackmessage: "The github repository number is : ${{ github.repository }}\n The workflow actor is ${{ github.autor }}"
    secrets:
      slackToken: ${{ secrets.SLACK_TOKEN }}
      deptrackapikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}

# jobs:
#   global-ci-resuse:
#     uses: YannickGbaka/ci-commons/.github/workflows/resuable-ci.yml@master
#     with: 
#       phpversion: '8.1'
#       slackmessage: "The github repository number is : ${{ github.repository }}\n The workflow actor is ${{ github.autor }}"

#     secrets:
#       slackToken: ${{ secrets.SLACK_TOKEN }}
#   sonarscanner:
#      uses: sonarsource/sonarqube-scan-action@master
#      env:
#       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


