name: reuse global ci
on:
  push:

jobs:
  global-ci-resuse:
    uses: YannickGbaka/ci-commons/.github/workflows/resuable-ci.yml@master
    with: 
      phpversion: '8.1'
      slack-message: "The github repository number is : ${{ github.repository }}\n The workflow actor is ${{ github.autor }}"

    secrets:
      slackToken: ${{ secrets.SLACK_TOKEN }}


