name: activityci
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'


env:
  SONAR_DEV_URL: sonar-dev.agenceemploijeunes.ci

jobs:
  init-project:
    name: init project job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@2.29.0
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql
      
      - name: Install composer dependancies
        run: |
          composer install

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Clear config
        run: php artisan config:clear

      - name: Run migration
        run: php artisan migrate -v

      - name: post to a slack channel
        id: post
        uses: slackapi/slack-github-action@v1.25
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          slack-message: "The job status is ${{ job.status }}\nThe build number is : \nThe github repository number is : ${{ github.repository }}\n The workflow actor is ${{ github.actor }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}



