name: "cd & cd pipeline"
on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

env:
  project_path: "/var/www/github-actions"

jobs:

  deployment:
    name: deployment on ec2 machine
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@v4

    - name: copy file via ssh password
      uses: appleboy/scp-action@0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: 22
        source: "."
        target: ${{ env.project-path }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: 22
        script: |
          sudo yum install git -y
          sudo dnf install php php-cli php-zip php-json -y
          sudo curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/bin/composer
          sudo chmod +x /usr/bin/composer
          sudo cd ${{ env.project-path }}
          sudo composer install --no-interaction 
          sudo chown -R apache.apache ${{ env.project-path }}
          sudo chmod -R 755 ${{ env.project-path }}
          sudo chmod -R 755 ${{ env.project-path }}/storage
          sudo chcon -R -t httpd_sys_rw_content_t ${{ env.project-path }}/storage
          sudo cp .env.example .env
          sudo php artisan key:generate
      




      


defaults:
  run:
    shell: bash
